---
name: Pull Request Validation

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "pypy3.9"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies and project
        run: |
          poetry install --no-interaction

      - name: Format code with black and isort
        run: |
          poetry run black .
          poetry run isort .

      - name: Test package
        run: |
          poetry install
          poetry run pytest

      - name: Test build wheel
        run: |
          poetry build
