---
name: Build, Test and Deploy Misprint

on:
  push:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]'

jobs:
  validate:
    uses: ./.github/workflows/main.yaml

  publish-wheel:
    needs: validate
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Build package
        run: |
          poetry build

      - name: Publish package
        if: success() && needs.validate.result == 'success'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
