---
name: Deploy misprint

on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]"

jobs:
  validate:
    uses: ./.github/workflows/main.yaml

  publish-wheel:
    if: success() && needs.validate.result == 'success'
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Publish package
        run: |
          python -m pip install --upgrade hatch
          hatch build
          hatch publish
